#goal definition
geometry_msgs/PoseStamped object_pose
---
#result definition
int32 SUCCESS = 0
int32 FAILED = -1
int32 FAILED_OUT_OF_REACH = -2
int32 result_code
geometry_msgs/Point suggestion
---
#feedback
# INITIAL=0
# EXECUTING=1
# FINISHED=2
uint8 curr_state
