#goal definition
geometry_msgs/Point object_position
geometry_msgs/Point aoi_position
bool fake_aoi
---
#result definition
bool success
int32 object_direction
---
#feedback
# INITIAL=0
# EXECUTING=1
# FINISHED=2
uint8 curr_state
