#goal definition
geometry_msgs/PoseStamped pose
float64 distance_tol
float64 orientation_tol
float64 planning_time
---
#result definition
bool success
---
#feedback
# INITIAL=0
# PLANNED=1
# EXECUTING=2
# FINISHED=3
uint8 curr_state